@startuml
class ucf.assignments.AppController {
~ int filter
- TableView<ListItem> table
- TableColumn<ListItem,Boolean> completed
- TableColumn<ListItem,String> description
- TableColumn<ListItem,String> date
+ void saveAll()
+ void newList(String)
+ void initialize(URL,ResourceBundle)
}


javafx.fxml.Initializable <|.. ucf.assignments.AppController
@enduml